# Generated by Django 5.1.1 on 2025-05-14 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_test", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="Category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="Category",
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="article_category",
                to="app_test.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_category",
                to="app_test.category",
            ),
        ),
    ]
